{
 "title": "nebula",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Number Of Metad Nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(nebula_metad_count)" }
   ]
  },
  {
   "title": "Number Of Graphd Nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(nebula_graphd_count)" }
   ]
  },
  {
   "title": "Number Of Storaged Nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(nebula_storaged_count)" }
   ]
  },
  {
   "title": "Insert Edge Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nebula_graphd_insert_edge_qps_count_60"
    }
   ]
  },
  {
   "title": "Insert Edge Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 3 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "nebula_graphd_insert_edge_latency_avg_60/1000"
    }
   ]
  },
  {
   "title": "Insert Edge Error",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nebula_graphd_insert_edge_error_qps_avg_60"
    }
   ]
  },
  {
   "title": "Insert Vertex Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nebula_graphd_insert_vertex_qps_count_60"
    }
   ]
  },
  {
   "title": "Insert Vertex Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "nebula_graphd_insert_vertex_latency_avg_60/1000"
    }
   ]
  },
  {
   "title": "Insert Vertex Error",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "nebula_graphd_insert_vertex_error_qps_avg_60"
    }
   ]
  },
  {
   "title": "GO Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nebula_graphd_go_qps_count_60" }
   ]
  },
  {
   "title": "Go Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "nebula_graphd_go_latency_avg_60/1000"
    }
   ]
  },
  {
   "title": "Go Error",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "nebula_graphd_go_error_qps_avg_60"
    }
   ]
  },
  {
   "title": "Fetch Edges Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nebula_graphd_fetch_edges_qps_count_60"
    }
   ]
  },
  {
   "title": "Fetch Vertices Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nebula_graphd_fetch_vertices_qps_count_60"
    }
   ]
  },
  {
   "title": "Find Path Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nebula_graphd_find_path_qps_count_60"
    }
   ]
  },
  {
   "title": "Delete Edge Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nebula_graphd_delete_edge_qps_count_60"
    }
   ]
  },
  {
   "title": "Delete Vertices Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nebula_graphd_delete_vertices_qps_count_60"
    }
   ]
  },
  {
   "title": "Update Edge Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nebula_graphd_update_edge_qps_count_60"
    }
   ]
  },
  {
   "title": "Update Vertex Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nebula_graphd_update_vertex_qps_count_60"
    }
   ]
  }
 ]
}