version: '3.7'
services:
  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: 
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    network_mode: host

  nebula-stats-exporter:
    image: vesoft/nebula-stats-exporter:${NEBULA_STATS_EXPORTER_VERSION:-v3.1.0}
    command:
      - --bare-metal
      - --bare-metal-config=/config.yaml
      - --listen-address=:9200
    ports:
      - 9200:9200
    volumes:
      - ${PWD}/nebula-stats-exporter.yaml:/config.yaml
    networks:
      - nebula-net

  prometheus:
    image: prom/prometheus:v2.1.0
    user: root
    volumes:
      - ${PWD}/prometheus.yaml:/etc/prometheus/prometheus.yml
      - ./data/prometheus:/prometheus:rw
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--storage.tsdb.retention=15d'
    ports:
      - 9090:9090
    networks:
      - nebula-net
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nebula-http-gateway:
    image: vesoft/nebula-http-gateway:${NEBULA_HTTP_GW_VERSION:-v2.2.0}
    volumes:
      - ${PWD}/nebula-http-gateway.conf:/root/conf/app.conf
    environment:
      USER: root
    ports:
      - 8080
    volumes:
      - ${UPLOAD_DIR}:${MAPPING_DOCKER_DIR}:rw
    networks:
      - nebula-net

  nebula-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 7003:7003
    volumes:
      - ${PWD}/dashboard.config:/app/config.json
    environment:
      USER: root
    networks:
      - nebula-net

networks:
  nebula-net:
    external: true
