global:
  scrape_interval:     5s
  evaluation_interval: 5s
scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: [
          'host.docker.internal:9100' # your node-exporter metrics endpoints 
        ]
  - job_name: 'nebula-stats-exporter'
    static_configs:
      - targets: [
         'nebula-stats-exporter:9200',  # nebula-stats-exporter metrics endpoints
        ]